### ISSUE TITLE
[資料錯誤] 紗羅 加入 比鄰星域

### ISSUE THREAD

**Issue by Mao606287** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#10]
**錯誤項目**

 - [ ] 名稱
 - [ ] 頻道連結
 - [x] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：紗蘿加入"比鄰星域" 團體新增為"比鄰星域"

**佐證**

2. 證明 1：https://twitter.com/ProximaSector/status/1466034746547269641
![image](https://user-images.githubusercontent.com/93981768/144257849-c57e3d65-f0a9-4290-af5f-75f636c310b9.png)

**Comment by nh60211as** [comment]
感謝回報。
預計將於明日 (2021/12/2) 更新資訊。

**Comment by nh60211as** [comment]
Confirmed added at 731ae3bc9ff974221d241f8c4ef7391df2f7c3c6.
