### ISSUE TITLE
[畢業登載] Makino Shiro Ch. 牧野白

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#101]
**畢業 Vtuber 資料**

 * 名稱：牧野白
 * 出道日期：2021/07/05
 * 畢業日期：2022/01/17
 * 畢業直播/影片連結：
 * 畢業公告：https://twitter.com/rectale_corp/status/1482822974667640832
 * YouTube 頻道連結：https://www.youtube.com/channel/UCbZcxNKrC0a6IZYBowvzAUg
 * Twitch 頻道連結：https://www.twitch.tv/makino_shiro
 * 團體：RECTALE
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 三個月內畢業

**Comment by nh60211as** [comment]
感謝回報。
已於 dd38956df50d40fc39da44213c77b4f47effb743 修改狀態。
