### ISSUE TITLE
[資料異動登載] 水上貓又

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#106]
**錯誤項目**

 - [x] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [X] 團體
 - [ ] 國家

**應更正項目**

1. 異動 1：團體異動為"異次緣"
2. 異動 2：名稱異動為"水上又"

**佐證**

1. 證明 1：https://www.youtube.com/channel/UCqj5KKNW8HoPPYjMQfnRznQ/about
2. 證明 2-1：https://www.youtube.com/channel/UCqj5KKNW8HoPPYjMQfnRznQ
3. 證明 2-2：https://twitter.com/oo840211

**Comment by nh60211as** [comment]
感謝回報。
預計將於 2022/01/26 05:55 修改。

**Comment by nh60211as** [comment]
Confirmed modified 5b3de0e002feae0da7e68535fb9d55b933fae710 .
