### ISSUE TITLE
[資料異動登載] 黒田翔隼Ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#107]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [X] 頻道連結
 - [ ] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：因帳號被BAN，頻道變更為 https://www.youtube.com/channel/UCQlwDhY0UNTL6N9ycFD76qQ

**佐證**

2. 證明 1：https://twitter.com/KurodaHayatoMY/status/1486965577189306368

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2022/01/30 修改。

**Comment by nh60211as** [comment]
Confirmed modified at 9318413134337dc6a688ee9b6046325de155d6e3 .
