### ISSUE TITLE
[資料異動登載] 吉姆Jimu. Channel

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#108]
**錯誤項目**

 - [ ] 名稱
 - [X] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [ ] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：已停止活動

**佐證**

2. 證明 1：https://twitter.com/Jimu0916
3. 證明 2：https://www.youtube.com/c/JIMUis87

**Comment by nh60211as** [comment]
感謝回報。
預計將於明日 2022/02/02 修改。

**Comment by nh60211as** [comment]
Confirmed modified at 74b3a3dbeb4af15e9013933dd2f132304d772f38 .
