### ISSUE TITLE
[資料異動登載] 異次緣

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#109]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [X] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：異次緣 團體解散 所有團員回歸個人

**佐證**

2. 證明 1：https://www.youtube.com/post/UgkxisxLvw1hVKN3W5hUVbZdP2riBC69GPrL

**Comment by nh60211as** [comment]
感謝回報。
預計將於今日 17:55 修改。

**Comment by nh60211as** [comment]
Confirmed modified at c4f96cd18a5f134276ff42fd1f213334a17b4aea .
