### ISSUE TITLE
[資料登載] 予樂樂 Leticia Yulele Ch.

### ISSUE THREAD

**Issue by paulliu159** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#11]
**新人/未收錄 Vtuber 資料**

 * 名稱：予樂樂 Leticia Yulele Ch.
 * YouTube 頻道連結：https://www.youtube.com/channel/UCUNA_bG3mRYaMSA1XgKjuHg
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [x] 出道三個月內
 - [x] 頻道訂閱/追隨人數大於 300 
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
以於今日 (2021/12/5)  a358a6179544414ca2acc781081724782d74c40e 收錄。
