### ISSUE TITLE
[資料登載] 奈咪Nami Ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#23]
**新人/未收錄 Vtuber 資料**

 * 名稱：冬月奈咪
 * YouTube 頻道連結：https://www.youtube.com/channel/UCr-ie9L4MdKWtmqrFAnGAgw
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [ ] 出道三個月內
 - [X] 頻道訂閱/追隨人數大於 300 
 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計將於明日 (2021/12/19) 收錄。

**Comment by nh60211as** [comment]
Confirmed added at d9cd458788768c19fb677b826c25b9d43a50ed5e .
