### ISSUE TITLE
[資料登載] 水縹そまる / Somaru Ch.

### ISSUE THREAD

**Issue by Mao606287** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#4]
**新人/未收錄 Vtuber 資料**

 * 名稱：水縹そまる / Somaru Ch.
 * YouTube 頻道連結：https://www.youtube.com/channel/UC3rmrlimhWzTsJ1BxY6-p1w
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [x] 出道三個月內
 - [x] 頻道訂閱/追隨人數大於 300 
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計將於明日 (2021/11/10) 收錄。

**Comment by nh60211as** [comment]
Confirmed added at 6266c7b951712d5769bccd97df047a67be48b7c7.
