### ISSUE TITLE
[資料登載] 屍屍Shishi

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#41]
**新人/未收錄 Vtuber 資料**

 * 名稱：屍屍
 * YouTube 頻道連結：https://www.youtube.com/channel/UC50VucABTfmaDxKk4L33QRQ
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [ ] 出道三個月內
 - [X] 頻道訂閱/追隨人數大於 300 
 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
此頻道已登錄，名稱為"屍屍Shishi"。
