### ISSUE TITLE
[資料登載] 荺希Yunxi Ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#42]
**新人/未收錄 Vtuber 資料**

 * 名稱：荺希
 * YouTube 頻道連結：https://www.youtube.com/channel/UCCXtrTVTHLG2lH4RXR9BpUA
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 出道三個月內
 - [ ] 頻道訂閱/追隨人數大於 300 
 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。確認實際上非出道三個月內。
由於 YouTube Data API 有每日請求資料的限制，目前只會將出道三個月內或是訂閱/追隨人數大於 300 的頻道顯示在網頁上。
待資料抓取程式可以更有效率地呼叫 API 後會解除此項限制。

**Comment by nh60211as** [comment]
預計於明日 2021/12/21 收錄。

**Comment by nh60211as** [comment]
Confirmed added at 7ef3d3ff9e36e02710f1ec792e493141673b3c05 .
