### ISSUE TITLE
[資料登載] Otis 騎士奧蒂斯Ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#45]
**新人/未收錄 Vtuber 資料**

 * 名稱：奧蒂斯
 * YouTube 頻道連結：https://www.youtube.com/channel/UC4GZXBxgeJYBhwS8ApHso_A
 * Twitch 頻道連結：
 * 團體：
 * 國家：MY

**Vtuber 目前活動狀態**

 - [X] 出道三個月內
 - [ ] 頻道訂閱/追隨人數大於 300 
 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計將於明日 (2021/12/19) 收錄。

**Comment by nh60211as** [comment]
Confirmed added at d9cd458788768c19fb677b826c25b9d43a50ed5e .
