### ISSUE TITLE
[資料登載] Bat ch. 蝙蝠貝特

### ISSUE THREAD

**Issue by nh60211as** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#47]
@貓樂火神 Nekoraku Hikami
不知道為什麼你發的資料登載都不見了。

**新人/未收錄 Vtuber 資料**

 * 名稱：蝙蝠貝特
 * YouTube 頻道連結：https://www.youtube.com/channel/UCxdsrzESGXN-OfXLanWW6QQ
 * Twitch 頻道連結：https://www.twitch.tv/vtuberbianfubeite
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [ ] 出道三個月內
 - [x] 頻道訂閱/追隨人數大於 300 
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
預計將於明日 (2021/12/19) 收錄。

**Comment by YueyuHoshizora** [comment]
@nh60211as 
他GitHub帳號沒申請好 被安控了…

**Comment by nh60211as** [comment]
==

**Comment by AzuChiron** [comment]
您好  我想要登記上列表

新人/未收錄 Vtuber 資料

名稱：亞茲凱龍 Azu Chiron Ch.
YouTube 頻道連結：https://www.youtube.com/channel/UCLiijofgtev1OlA64RUYz3Q
Twitch 頻道連結：https://www.twitch.tv/azuchiron
國家：TW

**Comment by YueyuHoshizora** [comment]
@AzuChiron 不是在這邊回應唷 有幫你另外處理了
@nh60211as 我有跟據他的資料 另外開一個 issue 給您處理了

**Comment by nh60211as** [comment]
Confirmed added at d9cd458788768c19fb677b826c25b9d43a50ed5e .
