### ISSUE TITLE
[資料登載]  【無声透明VTuber】強化人間【ミラージュコロイド系VTuber】

### ISSUE THREAD

**Issue by trombeningen** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#48]
**新人/未收錄 Vtuber 資料**

 * 名稱：
 * YouTube 頻道連結： https://www.youtube.com/channel/UCs_IVAqpWMnsb9bbDi7UMxw
 * Twitch 頻道連結： https://www.twitch.tv/trombeningen
 * 團體：
 * 國家：gensokyo

**Vtuber 目前活動狀態**

 - [ ] 出道三個月內
 - [x] 頻道訂閱/追隨人數大於 300 
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報，目前正在確認內容中。

**Comment by nh60211as** [comment]
預計於明日 2021/12/21 收錄。

**Comment by nh60211as** [comment]
Confirmed added at 7ef3d3ff9e36e02710f1ec792e493141673b3c05 .
