### ISSUE TITLE
[資料登載] 亞茲凱龍 Azu Chiron Ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#49]
**新人/未收錄 Vtuber 資料**

 * 名稱：
 * YouTube 頻道連結：https://www.youtube.com/channel/UCLiijofgtev1OlA64RUYz3Q
 * Twitch 頻道連結：https://www.twitch.tv/azuchiron
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 出道三個月內
 - [ ] 頻道訂閱/追隨人數大於 300 
 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

_Originally posted by @AzuChiron in https://github.com/TaiwanVtuberData/TaiwanVtuberData.github.io/issues/47#issuecomment-997318974_

**Comment by nh60211as** [comment]
感謝 @YueyuHoshizora 幫忙。
預計將於明日 (2021/12/20) 收錄。

**Comment by nh60211as** [comment]
Confirmed added at 3f5ef33ec5e5d36b875b63f6a7495c52caf86ed4 .
