### ISSUE TITLE
[資料登載] 千田悠依奈 ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#50]
**新人/未收錄 Vtuber 資料**

 * 名稱：千田悠依奈
 * YouTube 頻道連結：https://www.youtube.com/channel/UCz5iEiDcbA-NmMFxlAjvVEA
 * Twitch 頻道連結：
 * 團體：
 * 國家：MY

**Vtuber 目前活動狀態**

 - [ ] 出道三個月內
 - [ ] 頻道訂閱/追隨人數大於 300 
 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
由於 YouTube Data API 有每日請求資料的限制，目前只會將出道三個月內或是訂閱/追隨人數大於 300 的頻道顯示在網頁上。
待資料抓取程式可以更有效率地呼叫 API 後會解除此項限制。

**Comment by nh60211as** [comment]
預計於明日 2021/12/21 收錄。

**Comment by YueyuHoshizora** [comment]
@nh60211as API次數限制有解了?

**Comment by nh60211as** [comment]
@YueyuHoshizora 
> @nh60211as API次數限制有解了?

預設上限是10000扣打。

今天之前每次抓完整的列表要花5000扣打左右，所有我都會一次完整的列表跟兩次不完整的列表。

改程式碼之後變成3000扣打，所以我預計之後會每天抓兩次完整列表。

提升上限還沒申請，所以還有機會再提升更新頻率。

**Comment by YueyuHoshizora** [comment]
@nh60211as 可以多準備幾個Google 帳號
負責抓不同的資料段 (偷笑

**Comment by nh60211as** [comment]
Confirmed added at 7ef3d3ff9e36e02710f1ec792e493141673b3c05 .
