### ISSUE TITLE
[資料登載] Koana 考娜

### ISSUE THREAD

**Issue by bigclublee** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#51]
**新人/未收錄 Vtuber 資料**

 * 名稱：Koana 考娜
 * YouTube 頻道連結：https://www.youtube.com/channel/UCAtYhckbtAft3JploaYQU8g/featured
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [x] 出道三個月內或是尚未出道
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2021/12/21 收錄。

**Comment by nh60211as** [comment]
Confirmed added at 7ef3d3ff9e36e02710f1ec792e493141673b3c05 .
