### ISSUE TITLE
[資料登載] 雷門達也 Raimon Tatsuya Ch. 【新人HKVtuber】

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#52]
**新人/未收錄 Vtuber 資料**

 * 名稱：雷門達也
 * YouTube 頻道連結：https://www.youtube.com/channel/UCmIgns1R5DvBLANGZqNG3tA
 * Twitch 頻道連結：
 * 團體：
 * 國家：HK

**Vtuber 目前活動狀態**

 - [ ] 出道三個月內或是尚未出道
 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2021/12/22 收錄。

**Comment by nh60211as** [comment]
Confirmed added at 43be5cad2b804f197d3f35cbc3d4c75dd83c9f06 .
