### ISSUE TITLE
[未收錄登載] Elina ch.海月えりな

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#53]
**未收錄 Vtuber 資料**

 * 名稱：海月えりな
 * 出道日期：
 * 首次直播/影片連結：
 * YouTube 頻道連結：https://www.youtube.com/channel/UCofu6HsK6tZ76nEiW864Ubg
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
此頻道已登錄，名稱為"海月えりな"。
