### ISSUE TITLE
[未收錄登載] 橙楓

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#54]
**未收錄 Vtuber 資料**

 * 名稱：橙楓
 * 出道日期：
 * 首次直播/影片連結：
 * YouTube 頻道連結：https://www.youtube.com/channel/UCQCn_dhCUOMovITwedGMYcQ
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
目前找不到Vtuber的相關標籤或是自稱Vtuber，因此暫時不加入。

**Comment by YueyuHoshizora** [comment]
詢問過本人，已表明不是V，將關閉回報。

**Comment by nh60211as** [comment]
感謝確認。
