### ISSUE TITLE
[未收錄登載] Mari Ch. 舞綾真璃

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#55]
**未收錄 Vtuber 資料**

 * 名稱：舞綾真璃
 * 出道日期：2021年7月31日
 * 首次直播/影片連結：https://youtu.be/rZGFj1L8mJo
 * YouTube 頻道連結：https://www.youtube.com/channel/UCEbHRn4kPMzODDgsMwGhYVQ
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
已更新出道日期。
