### ISSUE TITLE
[未收錄登載] GuruGnome Ch. 咕咕嚕諾姆

### ISSUE THREAD

**Issue by bigclublee** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#56]
**未收錄 Vtuber 資料**

 * 名稱：咕咕嚕諾姆
 * 出道日期：
 * 首次直播/影片連結：https://www.youtube.com/watch?v=eVupYhCwG34
 * YouTube 頻道連結：https://www.youtube.com/channel/UCbbvq4QVq4DGCV-zcsQiGkQ
 * Twitch 頻道連結：https://www.twitch.tv/gurugnome
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [x ] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2021/12/24 收錄。

**Comment by nh60211as** [comment]
Confirmed added at 66c2d03047ae21e861ba0d24452c1673987fdd3f .
