### ISSUE TITLE
[未收錄登載] MixedUseless 個人勢Vtuber

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#59]
**未收錄 Vtuber 資料**

 * 名稱：MixedUseless
 * 出道日期：2021/07/31
 * 首次直播/影片連結：https://youtu.be/rR5ffU-cd9c
 * YouTube 頻道連結：https://www.youtube.com/channel/UCY8NkcB9LKrdlas-2SfmAIA
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2021/12/25 收錄。

**Comment by nh60211as** [comment]
Confirmed added at 47c276c2ec36cdefb5562ea0bb1eaa2445dded9a .
