### ISSUE TITLE
[資料登載] Neru Ch. 闇音ネル

### ISSUE THREAD

**Issue by Mao606287** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#6]
**新人/未收錄 Vtuber 資料**

 * 名稱：Neru Ch. 闇音ネル
 * YouTube 頻道連結：https://www.youtube.com/channel/UCymOeVRWRzjBrN_wfL7_xsg
 * Twitch 頻道連結：
 * 團體：AuroraLive
 * 國家：台灣

**Vtuber 目前活動狀態**

 - [x] 出道三個月內
 - [x] 頻道訂閱/追隨人數大於 300 
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by Mao606287** [comment]
**新人/未收錄 Vtuber 資料**

 * 名稱：Leina Ch. 蕾娜‧塔拉薩
 * YouTube 頻道連結：https://www.youtube.com/channel/UCSWJ3xMIqzzGsiHH5qGDD2A
 * Twitch 頻道連結：
 * 團體：AuroraLive
 * 國家：台灣

**Vtuber 目前活動狀態**

 - [ ] 出道三個月內
 - [ ] 頻道訂閱/追隨人數大於 300 
 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
闇音ネル 預計將於明日 (2021/11/28) 收錄。

蕾娜‧塔拉薩在另一個 issue  #8 處理

**Comment by nh60211as** [comment]
Confirmed add at 0080f7e16d4d9e0191bd32346f377973bb694bbd.
