### ISSUE TITLE
[資料錯誤] YakumoKen Ch2.八雲 劍_重生

### ISSUE THREAD

**Issue by bigclublee** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#60]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [x] 頻道連結
 - [ ] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：原帳號被盜開新頻道

**佐證**

2. 證明 1：新頻道：https://www.youtube.com/channel/UClA5YX0D1ejpeNh-oFcrXnw
3. 螢幕擷圖：https://twitter.com/Yakumo_Ken/status/1449601144481726467

**Comment by nh60211as** [comment]
感謝回報。
已於 66e160516ea4ed9fb81bc89d8501bfb01b76c461 更新頻道連結。
