### ISSUE TITLE
[新人登載] Heterogen NPO. 異次緣

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#63]
**新人 Vtuber 資料**

 * 名稱：Heterogen NPO.
 * 出道日期：2022/01/01
 * 首次直播/影片連結：
 * YouTube 頻道連結：https://www.youtube.com/channel/UCctw7o1KKzr8x5YdhuRunIw
 * Twitch 頻道連結：
 * 團體：異次緣
 * 國家：多國

**Vtuber 目前活動狀態**

 - [X] 出道一個月內或是尚未出道

**Comment by nh60211as** [comment]
感謝回報。
預計於下次資料更新收錄。

**Comment by nh60211as** [comment]
Confirmed added at 825d0d36c5357e8fa4a5085e17a8b64d63c44235 .
