### ISSUE TITLE
[資料錯誤] 罷工

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#65]
**錯誤項目**

 - [ ] 名稱
 - [X] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [ ] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：停止活動中 應改為 活動中

**佐證**

2. 證明 1：https://www.youtube.com/channel/UCLLbop68_DIW8bTRMOCO4iw

**Comment by nh60211as** [comment]
確認尚未停止活動。
於下次資料更新修正。

**Comment by nh60211as** [comment]
Confirmed modified at a80d0df035ed80671767bf8432c867c3c1bb2579 .
