### ISSUE TITLE
[資料錯誤] 多個頻道加入 異次緣

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#66]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [X] 團體
 - [ ] 國家

**應更正項目**

1. 更正：多個頻道加入團體 異次緣

**佐證**

2. 證明：下列頻道簡介
- https://www.youtube.com/channel/UCpl71UuimGfNeI438NYMasA/about
- https://www.youtube.com/channel/UCr-ie9L4MdKWtmqrFAnGAgw/about
- https://www.youtube.com/channel/UC9pS4r2ttkyOncFsrh_zjyg/about
- https://www.youtube.com/channel/UC8mp6R0E0uFeaoTYjZii0xw/about
- https://www.youtube.com/channel/UCLXRu8yatzwjUpaFD1o07KA/about
- https://www.youtube.com/channel/UCY8NkcB9LKrdlas-2SfmAIA/about

**Comment by nh60211as** [comment]
感謝回報。
預計於下次資料更新修改。

**Comment by nh60211as** [comment]
Confirmed add at 5d72a27c80891ffed4a39548178850acf4d23675 .
