### ISSUE TITLE
[資料錯誤] Luoyi ch.洛伊

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#68]
**錯誤項目**

 - [X] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [ ] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1："Luoyi ch.洛伊"名稱應為"月可洛伊"

**佐證**

2. 證明 1：https://www.youtube.com/channel/UC9pS4r2ttkyOncFsrh_zjyg/about

**Comment by nh60211as** [comment]
感謝回報。
將於下次資料更新修改名稱。

**Comment by nh60211as** [comment]
Confirmed modified at c75e0944d496d6aac98a2e9fb48aaba3b860ba68 .
