### ISSUE TITLE
[未收錄登載]  采彩 Aya Ch.

### ISSUE THREAD

**Issue by kelvin0511** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#72]
**未收錄 Vtuber 資料**

 * 名稱：采彩 Aya
 * 出道日期：2021年8月13日
 * 首次直播/影片連結：https://www.youtube.com/watch?v=SBdJ2KcGFRU&t=73s
 * YouTube 頻道連結：https://www.youtube.com/channel/UCtvpVPw7FXLJ7Fh2U9WbywA/featured
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2022/1/4 收錄。

**Comment by nh60211as** [comment]
Confirmed added at c0945a679a9e92cc1da56c7db8620ada67fbb40a .
