### ISSUE TITLE
[未收錄登載]  Keiya Tokihoro Ch. 時殲京矢

### ISSUE THREAD

**Issue by kelvin0511** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#73]
**未收錄 Vtuber 資料**

 * 名稱：時殲京矢 Tokihoro Keiya 
 * 出道日期：2021年8月22日
 * 首次直播/影片連結：https://www.youtube.com/watch?v=nVAfTVfc_Bg&t=1654s
 * YouTube 頻道連結：https://www.youtube.com/channel/UCPoeYBbHx8icdc8lAw4UPEQ
 * Twitch 頻道連結：
 * 團體：
 * 國家：HK

**Vtuber 目前活動狀態**

 - [x] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2022/1/4 收錄。

**Comment by nh60211as** [comment]
Confirmed added at c0945a679a9e92cc1da56c7db8620ada67fbb40a .
