### ISSUE TITLE
[資料異動登載] 多個頻道團體資訊錯誤

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#74]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [X] 團體
 - [ ] 國家

**應更正項目**

1. 下列頻道所屬團隊為 "破曉鴻羽" 並非 "VPS製幻工作室"
2. https://www.youtube.com/channel/UCBDFMn8a61FcfOI9NBZCF_A
3. https://www.youtube.com/channel/UCoEf8jZzm9aq7v2F4jsrdBQ
4. https://www.youtube.com/channel/UCzBi5O-K8VY-pHPy_ZBsAEA

**佐證**

5. 證明 1：已於2021/08/27 脫離VPS，另外成立團體勢 "破曉鴻羽"

**Comment by nh60211as** [comment]
感謝回報。
預計於下次資料更新修改。

**Comment by nh60211as** [comment]
Confirmed modified at 7686b3b9852977148809ccd947bee22dd1c2bf41 .
