### ISSUE TITLE
[資料異動登載] 屍屍Shishi

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#75]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [X] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：團體變更為 "異次緣"

**佐證**

2. 證明 1：https://www.youtube.com/channel/UC50VucABTfmaDxKk4L33QRQ/about

**Comment by nh60211as** [comment]
感謝回報。
預計於下次資料更新修改。

**Comment by nh60211as** [comment]
Confirmed modified at 7686b3b9852977148809ccd947bee22dd1c2bf41 .
