### ISSUE TITLE
[畢業登載] Eve Ch.廻時イヴ【香港VTuber】

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#76]
**新人 Vtuber 資料**

 * 名稱：
 * 出道日期：
 * 畢業日期：2022/01/05
 * 畢業直播/影片連結：
 * 畢業公告：https://twitter.com/Eve_hkv/status/1478462177048948736
 * YouTube 頻道連結：https://www.youtube.com/channel/UCdqGDN85zlycUw18cUuGLwQ
 * Twitch 頻道連結：
 * 團體：
 * 國家：HK

**Vtuber 目前活動狀態**

 - [X] 三個月內畢業

**Comment by nh60211as** [comment]
感謝回報。
預計將於明日 2022/1/6 修改。

**Comment by nh60211as** [comment]
Confirmed modified at bc639795de97d5920b2026aaa1b96c03fd7043d5 .
