### ISSUE TITLE
[資料異動登載] 無眠默莉絲

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#78]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [X] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：團體為 "V_up LIVE"

**佐證**

2. YT簡介：https://www.youtube.com/channel/UCimnmtiJeXq-VkLg2jL0qJw/about
3. 推特簡介：https://twitter.com/Molisi_0218

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2022/1/6 修改。

**Comment by nh60211as** [comment]
Confirmed modified at bc639795de97d5920b2026aaa1b96c03fd7043d5 .
