### ISSUE TITLE
[資料異動登載] 糖子 Tangzih

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#79]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [X] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [ ] 團體
 - [ ] 國家

**應更正項目**

1. 錯誤 1：出道日期無限延期（可能直接原地畢業）

**佐證**

2. 證明 1：https://twitter.com/TangZih/status/1478654359437475846

**Comment by nh60211as** [comment]
感謝回報。
稍後再進行處理。

**Comment by nh60211as** [comment]
暫時移除出道日期。

**Comment by nh60211as** [comment]
Close for now.
