### ISSUE TITLE
[畢業登載] 宇宇Yuyu ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#82]
**畢業 Vtuber 資料**

 * 名稱：
 * 出道日期：2021/10/27
 * 畢業日期：2022/01/07
 * 畢業直播/影片連結：
 * 畢業公告：https://twitter.com/EIYph6D9oXDueXS/status/1479137758279270402
 * YouTube 頻道連結：https://www.youtube.com/channel/UCo87mKF-LCbDC6tP80WbHNw
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 三個月內畢業

**Comment by nh60211as** [comment]
感謝回報。
預計於明日 2022/1/8 更新。

**Comment by nh60211as** [comment]
Confirmed added at 381efb24f783e2f847878fed5847ef2393125f04 .
