### ISSUE TITLE
[資料異動登載] Weed Yuna .雜草優奈

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#83]
**錯誤項目**

 - [ ] 名稱
 - [ ] 活動狀態
 - [ ] 出道日期
 - [ ] 畢業日期
 - [ ] 頻道連結
 - [X] 團體
 - [ ] 國家

**應更正項目**

1. 異動 1：團體變更為 "異次緣"

**佐證**

2. 證明 1：https://twitter.com/WeedYuna

**Comment by nh60211as** [comment]
感謝回報。
預計將於明日 2022/1/9 新增。

**Comment by nh60211as** [comment]
Confirmed added at b3ac8e980482a77ad92ab6c3c42ca953e3a34b97 .
