### ISSUE TITLE
[未收錄登載] 圖圖 tutu Ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#85]
**未收錄 Vtuber 資料**

 * 名稱：圖圖
 * 出道日期：2021/08/01
 * 首次直播/影片連結：https://www.youtube.com/watch?v=LR2Z8EtA1ds
 * YouTube 頻道連結：https://www.youtube.com/channel/UCr_2ldg9f44PvC-hNWnSvGg
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
Confirmed added at 8ebc87422406738affc8389eca0a22257f5e9893 .
