### ISSUE TITLE
[未收錄登載] Yuichi Ch. 翔太悠一

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#86]
**未收錄 Vtuber 資料**

 * 名稱：翔太悠一
 * 出道日期：2021/10/31
 * 首次直播/影片連結：https://www.youtube.com/watch?v=id0fOP55Upc
 * YouTube 頻道連結：https://www.youtube.com/channel/UCkhgz6O-fH8QOz8FQwvg4xA
 * Twitch 頻道連結：
 * 團體：
 * 國家：HK

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
Confirmed added at 8ebc87422406738affc8389eca0a22257f5e9893 .
