### ISSUE TITLE
[未收錄登載] 偵探貓化靈【HKVtuber】

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#87]
**未收錄 Vtuber 資料**

 * 名稱：偵探貓化靈
 * 出道日期：2021/11/06
 * 首次直播/影片連結：https://www.youtube.com/watch?v=1aVRYdhrTns
 * YouTube 頻道連結：https://www.youtube.com/channel/UCSvecUBizE0ROyH62KBFIZA
 * Twitch 頻道連結：
 * 團體：
 * 國家：HK

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
Confirmed added at 8ebc87422406738affc8389eca0a22257f5e9893 .
