### ISSUE TITLE
[未收錄登載] Kurona Ch.酒吞クロナ

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#88]
**未收錄 Vtuber 資料**

 * 名稱：酒吞クロナ
 * 出道日期：2021/10/05
 * 首次直播/影片連結：https://www.youtube.com/watch?v=TNv3dLwDIes
 * YouTube 頻道連結：https://www.youtube.com/channel/UCYPr6jNySMcfpjheFi61U8w
 * Twitch 頻道連結：
 * 團體：
 * 國家：HK

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
此頻道已登錄，名稱為"酒吞クロナ"。
