### ISSUE TITLE
[未收錄登載] Tsubaki Ch.兎澤つばき

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#89]
**未收錄 Vtuber 資料**

 * 名稱：兎澤つばき
 * 出道日期：2021/05/21
 * 首次直播/影片連結：https://www.youtube.com/watch?v=3KYqLXnhXCc
 * YouTube 頻道連結：https://www.youtube.com/channel/UC7FTe-NHQqBvTjzli6p0Mnw
 * Twitch 頻道連結：
 * 團體：
 * 國家：MY

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
Confirmed added at 8ebc87422406738affc8389eca0a22257f5e9893 .
