### ISSUE TITLE
[未收錄登載] Shin Channel

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#91]
**未收錄 Vtuber 資料**

 * 名稱：Shin
 * 出道日期：2020/10/26
 * 首次直播/影片連結：https://www.youtube.com/watch?v=fWXEtHp7-I0
 * YouTube 頻道連結：https://www.youtube.com/channel/UCxy7FuvDFYA9-mPM8DdCoUw
 * Twitch 頻道連結：
 * 團體：
 * 國家：MY

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
Confirmed added at 8ebc87422406738affc8389eca0a22257f5e9893 .
