### ISSUE TITLE
[未收錄登載] Akiharu Sora Ch. 秋晴ソラ

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#92]
**未收錄 Vtuber 資料**

 * 名稱：秋晴ソラ
 * 出道日期：2021/11/07
 * 首次直播/影片連結：https://www.youtube.com/watch?v=1mptt4M0s-U&t
 * YouTube 頻道連結：https://www.youtube.com/channel/UC6Uj1JkLSaapKpngXEyDF5g
 * Twitch 頻道連結：
 * 團體：
 * 國家：MY

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
Confirmed added at 8ebc87422406738affc8389eca0a22257f5e9893 .
