### ISSUE TITLE
[新人登載] Merlin_Durand 杜蘭德·梅林 Ch.

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#96]
**新人 Vtuber 資料**

 * 名稱：杜蘭德
 * 出道日期：2022/01/05
 * 首次直播/影片連結：https://www.youtube.com/watch?v=bupYNccW4EE
 * YouTube 頻道連結：https://www.youtube.com/channel/UCeRf9OFQldxPh877op-QLjA
 * Twitch 頻道連結：
 * 團體：
 * 國家：TW

**Vtuber 目前活動狀態**

 - [X] 出道一個月內或是尚未出道

**Comment by nh60211as** [comment]
Confirmed added at 8ebc87422406738affc8389eca0a22257f5e9893 .
