### ISSUE TITLE
[未收錄登載] Hezaki Ch.鬣崎ミナミ

### ISSUE THREAD

**Issue by YueyuHoshizora** [TaiwanVtuberData/TaiwanVtuberData.github.io-Legacy#98]
**未收錄 Vtuber 資料**

 * 名稱：鬣崎ミナミ
 * 出道日期：2021/04/10
 * 首次直播/影片連結：https://youtu.be/W4D3dwXp8Pk
 * YouTube 頻道連結：https://www.youtube.com/channel/UCqfmSgWmX4e_wUylAazxrpQ
 * Twitch 頻道連結：
 * 團體：
 * 國家：MY

**Vtuber 目前活動狀態**

 - [X] 最近一個月內有直播或是影片(YouTube Shorts 不算)

**Comment by nh60211as** [comment]
感謝回報。
此頻道已登錄，名稱為"鬣崎米娜米"，將修改名稱為"鬣崎ミナミ"。

**Comment by nh60211as** [comment]
Confirmed modified at 8ebc87422406738affc8389eca0a22257f5e9893 .
